### ISSUE TITLE
Change height of top panel

### ISSUE THREAD

**Issue by Dobbie03** [4ban/awesome-pro#3]
Love this theme and am very new to Awesome.  How do I change the height of the top panel?

**Comment by 4ban** [comment]
Hi, thanks for the feedback. 
You need to change the height property in the rc.lua file on line 470. [Here](https://github.com/4ban/awesome-pro/blob/master/rc.lua#L470) 

But the top panel is based on images that used as backgrounds for widgets, so you'll find some visual issues probably.

**Comment by Dobbie03** [comment]
Thanks for the reply.  Yeah one of the downsides to a hidpi screen unfortunately.
